spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: foo=bar, baz
        healthCheckPath:  /health
        healthCheckInterval: 15s
#        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  application:
    name: app
server:
  port: 8880
